access_token = 'bd9a6d3b-8052-4151-9369-391029a5a37c'
device_id = 'ce226804-02b4-4587-aa0f-0d0b14126717'
license_key = 'Q2o41Kn0-9eL8Mf37-b12r5h9E'
private_key = '0GrTEPRBcLYV+AfYJPpr2FU8NC7m/fknWbNWM+p3pnc='
